[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "alembic upgrade head && python -m bot.main"

